CREATE TABLE IF NOT EXISTS encrypted_wallets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    wallet_id TEXT UNIQUE NOT NULL,
    encrypted_data BLOB NOT NULL,
    salt BLOB NOT NULL,
    nonce BLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
