[package]
name = "market-maker-cosmos-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
cosmrs = "0.15"                                     # or the latest version
prost = "0.12"
prost-types = "0.12"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
anyhow = "1.0"
hex = "0.4.3"
sha2 = "0.10"
ripemd = "0.1.3"
base64 = "0.22.1"
serde = "1.0.219"

bip32 = { version = "0.5", default-features = false, features = ["bip39"] }
rpassword = "7"                                                             # read without echo
[build-dependencies]
prost-build = "0.12"
